sensor:
## Weather climatecell.co
  - platform: climacell
#    api_key: !secret climacell_api_version_4
    api_key: isBozB6e05nj8VtHV1fHBIgK25T33L8p
    name: cc
    latitude: !secret latitude
    longitude: !secret longitude
    monitored_conditions:
      realtime:
        - weather_condition
        - temperature
        - humidity
        - visibility
        - cloud_cover
        - precipitation
        - precipitation_type
        - pressure
        - wind_speed
        - wind_direction
        - wind_gust
        - moon_phase
        - sunset
        - sunrise
      forecast:
        - weather_condition
        - temperature
        - precipitation
        - precipitation_probability
    scan_interval:
      # At least one of these must be specified:
      days: 0
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0