
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  themes: !include themes/theme.yaml


light:
  - platform: flux_led
    automatic_add: true

input_text:
  custom_station:
    name: Radio URL
    icon: mdi:link-variant

#lovelace:
#  mode: yaml
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate
    base_url: https://h4l3uxr88jnur3ik6512gyo4n1n8qbtn.ui.nabu.casa
#    base_url: https://192.168.0.20
  - platform: voicerss
    api_key: !secret voicerss_api_key

#ble_monitor:
#  rounding: True
#  decimals: 2
#  period: 60
#  log_spikes: True
#  use_median: False
#  active_scan: True
#  hci_interface: 1
#  batt_entities: True
#  report_unknown: True

####################
###              ###
###    SEEDBOX   ###
###              ###
####################
transmission:
  host: 192.168.0.20
ombi:
  host: 192.168.0.20
  username: !secret ombi_username
  api_key: !secret ombi_api
  port: 3579




map:

stt:

wake_on_lan:

browser_mod:
  devices:
    e92cff65-59c90904:
      name: browsermod_brenthassioe92cff6559c90904
#      camera: true
    ff7477a8-b6cad842:
      name: browsermod_kitchenhassioff7477a8b6cad842
#      camera: true
    4b39ae48-522d3d41:
      name: browsermod_brentchrome4b39ae48522d3d41
#       camera: true
    2b9a6c53 d34ea3cb:
      name: browsermod_remotelivingroom
#       camera: true
    1393f59e d787631e:
      name: browsermod_brentmi9
#       camera: true
#glances:
#  - host: 192.168.0.20
  

mqtt:
  broker: !secret nucserver_ip  # Remove if you want to use builtin-in MQTT broker
  port: 1883
  discovery: true
  client_id: homeassistant
  username: !secret mqtt_user
  password: !secret mqtt_password
  birth_message:
    topic: 'homeassistant/bridge/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/bridge/status'
    payload: 'offline'

image_processing:
#  - platform: doods
#    url: "http://192.168.0.20:8080"
#    detector: default
#    scan_interval: 1
#    confidence: 60
#    source:
#      - entity_id: camera.ffmpeg_driveway
##      - entity_id: camera.server_room_phone
#    file_out:
#      - /config/www/doods/doods.jpg
#      - "/config/www/doods/{{ camera_entity.split('.')[1] }}_latest.jpg"
##      - "/config/www/doods/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
##    labels:
##      - name: person
##        confidence: 60

  - platform: deepstack_object
    ip_address: !secret nucserver_ip
    port: 5000
    # api_key: !secret deepstack_api_key ## No longer required
    scan_interval: 5
    save_file_folder: /config/snapshots/
#    always_save_latest_jpg: true
    save_timestamped_file: True
    targets:
      - target: person
        confidence: 70
      - target: vehicle
        confidence: 80
      - target: car
        confidence: 80
    source:
      - entity_id: camera.ffmpeg_xiaomi_test_camera

  - platform: deepstack_face
    ip_address: !secret nucserver_ip
    port: 5000
#    api_key: !secret deepstack_api_key
    timeout: 20
    detect_only: False
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    show_boxes: True
    source:
      - entity_id: camera.ffmpeg_xiaomi_test_camera

  - platform: deepstack_object
    ip_address: !secret nucserver_ip
    port: 5000
    # api_key: !secret deepstack_api_key ## No longer required
    scan_interval: 5
    save_file_folder: /config/snapshots/
#    always_save_latest_jpg: true
    save_timestamped_file: True
    targets:
      - target: person
        confidence: 70
      - target: vehicle
        confidence: 80
      - target: car
        confidence: 80
    source:
      - entity_id: camera.ffmpeg_test_driveway

  - platform: deepstack_face
    ip_address: !secret nucserver_ip
    port: 5000
#    api_key: !secret deepstack_api_key
    timeout: 20
    detect_only: False
    save_file_folder: /config/snapshots/
    save_timestamped_file: True
    show_boxes: True
    source:
      - entity_id: camera.ffmpeg_test_driveway


vacuum:
  - platform: xiaomi_miio
    host: 192.168.0.59
    token: !secret vacuum_xiaomi_miio.token
#smartthinq:
#    token: 57fadb45da36c8f330f798f4adb44631cd91fd1dd4a3fcab87292d32fc074794182cfd0610b1f742e827a15b2d9aa5c2
#    token: !secret smartthinq_token
#    region: NZ
#    language: en-US

input_boolean:
  daily_vacuum_first_run:
    name: Daily Vacuum First Run
    initial: 'off'
  disable_daily_vacuum:
    name: Disable Daily Vacuum Automation
    initial: 'off'
  disable_dustbin_notification:
    name: Disable Dustbin Notification
    initial: 'off'
  ytube_music_player_playcontinuous:
    initial: true
    name: "Countinuous Playback"

################################################################################
##                       DEVICE TRACKER                                       ##
################################################################################
device_tracker:
  - platform: bluetooth_tracker

#  - platform: bluetooth_le_tracker
#    interval_seconds: 30
#    consider_home: 180
#    track_battery: true
#    track_new_devices: true

#  - platform: netgear
#    host: 192.168.0.1
#    password: !secret netgear_router_password


smartir:

fan:
  - platform: smartir
    name: Dimplex Heater Fan - smartir
    unique_id: dimplex_heater_fan
    device_code: 1000
    controller_data: remote.living_room_ir_remote
#    power_sensor: binary_sensor.fan_power


binary_sensor:
  - platform: ffmpeg_motion
    input: -rtsp_transport tcp -i rtsp://192.168.0.60:8554/unicast
#    extra_arguments: -pred 1 -q:v 2
    changes: 2
    reset: 2
#    repeat: 2
#    repeat_time: 3
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/face"
#    off_delay: 
    name: "Face Detected"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion
  - platform: mqtt
    state_topic: "wallpanel/mywallpanel/sensor/motion"
    name: "Motion"
    payload_on: '{"value":true}'
    payload_off: '{"value":false}'
    device_class: motion
  - platform: ping
    name: google_wifi_ping
    host: 192.168.0.2
  - platform: ping
    name: tplink_tl_wa901nd_ping
    host: 192.168.0.3
  - platform: ping
    name: NUC Server
    host: !secret nucserver_ip
  - platform: ping
    name: Samsung TV
    host: !secret samsung_tv_ip
    scan_interval: 10
  - platform: ping
    name: RMMINI-18-51-64 - ping
    host: 192.168.0.30
  - platform: ping
    name: MI Remote - ping
    host: 192.168.0.32
  - platform: ping
    name: JBL Link Soundbar - Android TV - ping
    host: 192.168.0.36
  - platform: ping
    name: FreeView - Android TV - ping
    host: 192.168.0.37
  - platform: ping
    name: Mi Box - PLay Room - Android TV - ping
    host: 192.168.0.40
  - platform: ping    
    name: Yeelink Light - Ella's Bedroom - ping
    host: 192.168.0.45
  - platform: ping
    name: Xiaomi Camera Hub G2 - ping
    host: 192.168.0.46
  - platform: ping
    name: Google Mini - Master Bedroom Speaker - ping
    host: 192.168.0.47
  - platform: ping
    name: Google Home - Kitchen Speaker - ping
    host: 192.168.0.48
  - platform: ping
    name: Xiaomi Vacuum - ping
    host: !secret xiaomi_vacuum_host
    scan_interval: 10
  - platform: ping
    name: Seed Box - RPi - ping
    host: 192.168.0.22
    scan_interval: 10
  - platform: ping
    host: www.google.com
    name: google

################################################################################
##                       SWITCH                                               ##
################################################################################
switch:

  - platform: zoneminder
    command_on: Modect
    command_off: Monitor
  - platform: template
    switches:
      media_lounge_on_off:
        friendly_name: Turn Media Lounge On/Off
        value_template: "{{ is_state('binary_sensor.samsung_tv', 'on') }}"
        turn_on:
          service: script.turn_on_media_lounge
        turn_off:
          service: script.turn_off_media_lounge
        entity_picture_template: >-
          {% if is_state('binary_sensor.samsung_tv', 'on') %}
            /local/pictures/icons/on_switch.png
          {% else %}
            /local/pictures/icons/off_switch.png
          {% endif %}
#  - platform: netgear_enhanced
#    host: !secret netgear_router_ip
#    username: !secret netgear_router_login
#    password: !secret netgear_router_password
#    resources:
#      - 'access_control'
#      - 'traffic_meter'
#      - 'parental_control'
#      - 'qos'
#      - '2g_guest_wifi'
#      - '5g_guest_wifi'
#      - 'run_speed_test'
#      - 'reboot'


remote:
#  - platform: xiaomi_miio #model:chuangmi.remote.v2
#    name: "Xiaomi IR Remote Kitchen"
#    host: 192.168.0.32
#    token: 80519b5a1068ebf27ad9421e6ee169e6


panel_iframe:
  wikiint:
    title: wiki
    icon: mdi:wikipedia
    url: http://192.168.0.20:3000
  ideint:
    title: IDE Int
    icon: mdi:code-braces
    url: https://192.168.0.20:8321
  flextv:
    title: Flex TV
    icon: mdi:plex
    url: https://192.168.0.20:1778
#  zm:
#    title: ZM
#    url: http://192.168.0.20:8082/zm/
  zmhttps:
    title: ZM
    url: https://192.168.0.20:8443/zm/
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: https://192.168.0.20:8181

zoneminder:
  - host: 192.168.0.20:8443
    path: /zm/
    ssl: true
    verify_ssl: false
    
ffmpeg:
stream:




notify:
  - name: HA
    platform: pushsafer
    private_key: !secret pushsafer


homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config/snapshots
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
      allow_bypass_login: true
    - type: homeassistant

proximity:
  home_brent:
    devices:
      - device_tracker.brent_mi_9
    tolerance: 50
    unit_of_measurement: km
  home_claudia:
    devices:
      - device_tracker.pixel_xl
    tolerance: 50
    unit_of_measurement: km
  home_residents:
    devices:
      - device_tracker.brent_mi_9
      - device_tracker.pixel_xl
    tolerance: 50
    unit_of_measurement: km

media_player: !include media_player.yaml
climate: !include climate.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include cameras.yaml
rest_command: !include rest_command.yaml
sensor: !include sensor.yaml
zone: !include zones.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml